version: '3.1'

networks:
  default:
    external:
      name: hadoopnet
services:
  hadoop8:
    image: zookeeper
    restart: always
    container_name: hadoop8
    hostname: hadoop8 
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=hadoop9:2888:3888;2181 server.3=hadoop10:2888:3888;2181

  hadoop9:
    image: zookeeper
    restart: always
    container_name: hadoop9
    hostname: hadoop9 
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=hadoop8:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=hadoop10:2888:3888;2181

  hadoop10:
    image: zookeeper
    restart: always
    container_name: hadoop10
    hostname: hadoop10 
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=hadoop8:2888:3888;2181 server.2=hadoop9:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
